const dogFetchActionTypes = {
  FETCH_DOG_START: "FETCH_DOG_START",
  FETCH_DOG_SUCCESS: "FETCH_DOG_SUCCESS",
  FETCH_DOG_FAILURE: "FETCH_DOG_FAILURE",
  FETCH_BREEDS_START: "FETCH_BREEDS_START",
  FETCH_BREEDS_SUCCESS: "FETCH_BREEDS_SUCCESS",
  FETCH_BREEDS_FAILURE: "FETCH_BREEDS_FAILURE",
};

export default dogFetchActionTypes;
